String SPLASH_SCREEN='SPLASH_SCREEN';
String HOME_SCREEN='HOME_SCREEN';
String LOGIN_FORM='LOGIN_FORM';
String ITEM_DETAILS_SCREEN='ITEM_DETAILS_SCREEN';
String GRID_ITEM_DETAILS_SCREEN='GRID_ITEM_DETAILS_SCREEN';

